---
# Reverse Proxy Handler Configuration

# If HTTP 2.0 protocol will be used to connect to target servers
http2Enabled: ${proxy.http2Enabled:true}

# If TLS is enabled when connecting to the target servers
httpsEnabled: ${proxy.httpsEnabled:true}

# Target URIs
hosts: ${proxy.hosts:http://localhost:8081,http://localhost:8082,http://localhost:8083}

# Connections per thread to the target servers
connectionsPerThread: ${proxy.connectionsPerThread:20}

# Max request time in milliseconds before timeout
maxRequestTime: ${proxy.maxRequestTime:1000}

# Rewrite Host Header with the target host and port and write X_FORWARDED_HOST with original host
rewriteHostHeader: ${proxy.rewriteHostHeader:true}

# Reuse XForwarded for the target XForwarded header
reuseXForwarded: ${proxy.reuseXForwarded:false}

# Max Connection Retries
maxConnectionRetries: ${proxy.reuseXForwarded:3}
