FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

USER root

ENV GROUP_NAME=networknt \
    GROUP_ID=1000 \
    USER_NAME=networknt \
    USER_UID=1000

RUN groupadd -g ${GROUP_ID} -r ${GROUP_NAME} && \
    useradd --no-log-init -u ${USER_UID} -r -g ${GROUP_NAME} ${USER_NAME}

# Add the jar file
ADD target/light-proxy.jar server.jar

RUN ls -al ./
  
# change permissions of the directory
RUN mkdir -p /config && \
    chown -R ${USER_NAME}:0 "/config" && \
    find "/config" -type d -exec chmod 750 {} \; && \
    find "/config" -type f -exec chmod 640 {} \; && \

RUN ls -al / && ls -al /config && ls -al ./

# Port available to the world outside of this container
EXPOSE 8080

USER ${USER_UID}

CMD ["/bin/sh","-c","java -Dlight-4j-config-dir=/config -Dlogback.configurationFile=/config/logback.xml -jar server.jar"]